version: '3.3'

services:
  pythonapp:
    container_name: pythonapp
    image: pythonapp
    build: .
    ports:
      - "8081:81"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@email.com
      - PGADMIN_DEFAULT_PASSWORD=test123
    depends_on:
      - db
    
  db:
    container_name:  db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
